'''
Created on Jun 24, 2014

@author: dbhage

Module responsible for getting compositions
'''

from util.io import get_lines

def get_compositions(compositions_file, topics_ignored=[]):
    '''
    Get compositions from composition_file
    @param compositions_file: the path to the text file containing compositions. This file is generated by Mallet.
    @param topics_ignored: list of integers representing topics to be ignored
    @return: dict with document name as key and Composition object as value
    '''
    lines = get_lines(compositions_file)
    compositions = parse_compositions(lines, topics_ignored)
    return compositions

def parse_compositions(lines, topics_ignored=[]):
    '''
    Get compositions objects from a file
    @param topics_ignored: list of integers representing topics to be ignored
    @return: dict with document name as key and Composition object as value
    '''
    if lines is None or lines == []:
        return None
    
    compositions = dict()

    for line in lines[1:]:
        composition = Composition()
        line = line.replace('\n', '')
        split_line = line.split()
        composition.doc_no = int(split_line[0])
        composition.name = split_line[1].split('/')[-1]

        # get topic proportions
        counter = 2
        main_topic = (-1, 0)
        
        while counter < len(split_line):
            topic = int(split_line[counter])
            
            if topic in topics_ignored:
                counter += 2
                continue
            
            proportion = float(split_line[counter + 1])
            composition.add_topic_proportion(topic, proportion)
            
            if proportion > main_topic[1]:
                main_topic = (topic, proportion) 
            
            counter += 2
        
        composition.main_topic = main_topic[0]
        compositions[composition.name] = composition
        
    return compositions

def save_compositions_to_file(compositions, txt_file_name):
    with open(txt_file_name, 'w') as fd:
        fd.write("#doc name topic proportion ...\n")
        for (a_name, composition) in compositions.items():
            fd.write(str(composition.doc_no) + '\t')
            fd.write(a_name + '\t')
            fd.write(str(composition.main_topic) + ' ' + str(composition.topic_proportions[composition.main_topic]))
            fd.write('\n')

class Composition(object):
    '''
    Data Structure to represent a composition for a document. 
    '''
    def __init__(self):
        '''
        Constructor
        '''
        self.doc_no = -1
        self.name = ''
        self.topic_proportions = dict()
        self.main_topic = None
        
    def add_topic_proportion(self, topic, proportion):
        '''
        @precondition: self.topic_proportions must have been initialised with an empty dict
        '''
        self.topic_proportions[topic] = proportion
        
    def __str__(self):
        return str(self.doc_no) + " " + self.name + " " + str(self.topic_proportions)